---
settings:
  name: Release Notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: BlueXP版本說明
    url: "/index.html"
  - title: 最近的變更
    url: "/whats-new.html"
  - title: BlueXP索引
    url: "/release-notes-index.html"
homepage:
  tiles:
  - title: 新增功能
    links:
    - title: 最新的BlueXP變更
      url: whats-new.html
  - title: 按服務提供版本說明
    links:
    - title: 版本資訊索引
      url: release-notes-index.html
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP網站部落格
      url: https://cloud.netapp.com/blog
    - title: 雲端網路研討會
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有BlueXP文件
