---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam' 
summary: 瞭解最新的雲端服務變更、這些變更是BlueXP平台的一部分。 
---
= 最新的BlueXP變更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解最新的雲端服務變更、這些變更是BlueXP平台的一部分。如需完整的發行記錄、請前往 link:release-notes-index.html["完整的版本資訊"] 針對每項個別服務。



== 管理功能

本節說明與BlueXP管理功能相關的新功能：帳戶、連接器、雲端供應商認證等。



=== 2025 年 12 月 5 日



==== 連接器 3.9.52

此版本的 BlueXP  Connector 包括少量的安全性改善和錯誤修正，以及一些其他更新。

目前、 3.9.52 版本適用於標準模式和受限模式。



===== 支援 Docker 27 和 Docker 28

Connector 現在支援 Docker 27 和 Docker 28 。



==== BlueXP  中提供 Keystone 管理功能

BlueXP  中的 NetApp Keystone 試用版已新增對 Keystone 管理的存取權。您可以從 BlueXP  左側導覽列存取 NetApp Keystone Beta 的登錄頁面。



=== 2025 年 4 月 14 日



==== 連接器 3.9.51

此版本的 BlueXP Connector 包括少量的安全性改善和錯誤修正。

目前、 3.9.51 版本適用於標準模式和受限模式。



==== BlueXP  身分識別與存取管理（ IAM ）

* 沒有組織管理員，資料夾或專案管理員的使用者，必須指派勒索軟體保護角色，才能存取勒索軟體保護。您可以指派使用者兩種角色之一：勒索軟體保護管理員或勒索軟體保護檢視器。
* 沒有組織管理員，資料夾或專案管理員的使用者必須指派 Keystone 角色，才能存取 Keystone 。您可以指派使用者兩個角色之一： Keystone 管理員或 Keystone 檢視器。
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["瞭解存取角色。"^]

* 如果您具有組織管理員或資料夾或專案管理員角色，現在您可以將 Keystone 訂閱與 IAM 專案建立關聯。將 Keystone 訂閱與 IAM 專案建立關聯可讓您控制 BlueXP  中 Keystone 的存取。




=== 2025 年 3 月 28 日



==== 私有模式版本（ 3.9.50 ）

現在可從下載新的私有模式版本 https://mysupport.netapp.com/site/downloads["NetApp 支援網站"^]

3.9.50 版本包含下列 BlueXP  元件和服務的更新。

[cols="3*"]
|===
| 元件或服務 | 此版本隨附的版本 | 自上一次私有模式版本以來所做的變更 


| 連接器 | 3.9.50 ， 3.9.49 | 請移至， https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["BlueXP  Connector 網頁的新功能"]並參閱 3.9.50 和 3.9.49 版隨附的變更。 


| 備份與還原 | 2025 年 3 月 17 日 | 前往 https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["BlueXP  備份與還原頁面的新功能"^]並參閱 2024 年 3 月版本中所包含的變更。 


| 分類 | 2025 年 3 月 10 日（版本 1.41 ） | 請移至， https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["BlueXP  分類頁面的新功能"^]並參閱 1.38 至 1.371.41 版本中所包含的變更。 
|===
如需更多關於私有模式的詳細資訊、包括如何升級、請參閱下列內容：

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["瞭解私有模式"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["瞭解如何以私有模式開始使用 BlueXP"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["瞭解如何在使用私有模式時升級 Connector"]




== 警示



=== 2024 年 10 月 7 日



==== BlueXP  警示清單頁面

您可以快速識別容量低或效能低的 ONTAP 叢集、評估可用度並識別安全風險。您可以檢視容量、效能、保護、可用度、安全性和組態等相關警示。



==== 警示詳細資料

您可以深入瞭解警示詳細資料並尋找建議。



==== 檢視連結至 ONTAP 系統管理員的叢集詳細資料

透過 BlueXP  警示、您可以檢視與 ONTAP 儲存環境相關的警示、並深入瞭解連結至 ONTAP 系統管理員的詳細資料。

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["瞭解 BlueXP  警示"]。



== Amazon FSX for ONTAP Sf



=== 2025 年 04 月 5 日



==== Tracker 回應支援

Tracker 現在提供 API 回應，讓您可以查看與工作相關的 REST API 輸出。



==== AWS Secrets Manager 的連結驗證支援

您現在可以選擇使用 AWS Secrets Manager 的機密來驗證連結，這樣就不需要使用儲存在 BlueXP  工作負載中的認證資料。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["使用 Lambda 連結連線至適用於 ONTAP 檔案系統的 FSX"]



==== 為 ONTAP 檔案系統實作 FSX 的最佳實務做法

BlueXP  工作負載提供儀表板，讓您檢視檔案系統組態架構良好的狀態。您可以利用此分析，為 ONTAP 檔案系統的 FSX 實作最佳實務做法。檔案系統組態分析包括下列組態： SSD 容量臨界值，排程本機快照， ONTAP 備份排程的 FSX ，資料分層和遠端資料複寫。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["瞭解檔案系統組態的架構良好分析"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["為您的檔案系統實作最佳實務做法"]




==== 架構良好的檔案系統問題通知

在 BlueXP  主控台中，架構良好問題的 ONTAP 檔案系統適用的 FSX 現在會在 Canvas 中顯示通知，指出檔案系統何時有問題需要修正。



==== 更新的權限術語

工作負載原廠使用者介面與文件現在使用「唯讀」來指稱讀取權限，而「讀取寫入」則指自動化權限。



=== 2025 年 3 月 30 日



==== IAM ： SimulatePermissionPolicy 權限更新

現在，您可以在新增額外的 AWS 帳戶認證或新增 GenAI 工作負載等新工作負載功能時，從 BlueXP  主控台管理 `iam:SimulatePrincipalPolicy`權限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["權限參考變更記錄"^]



=== 2025 年 3 月 02 日



==== Tracker 中的 CloudShell 事件

每當您使用 CloudShell 從 BlueXP  工作負載執行適用於 ONTAP 作業的 FSX 時，事件都會顯示在 Tracker 中。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["瞭解如何在 BlueXP  中監控和追蹤適用於 ONTAP 作業的 FSX"^]



== Amazon S3儲存設備



=== 2023 年 3 月 5 日



==== 能夠從BlueXP新增庫位

您已能在BlueXP畫版上檢視Amazon S3時段長時間。現在您可以直接從 BlueXP  新增新的貯體、並變更現有貯體的屬性。 https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["瞭解如何新增Amazon S3儲存庫"]。



== Azure Blob 儲存設備



=== 2023 年 6 月 5 日



==== 能夠從 BlueXP 新增儲存帳戶

您已有一段時間可以在 BlueXP Canvas 上檢視 Azure Blob Storage 。現在您可以直接從 BlueXP  新增儲存帳戶、並變更現有儲存帳戶的內容。 https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["瞭解如何新增 Azure Blob 儲存帳戶"]。



== Azure NetApp Files



=== 2025 年 1 月 13 日



==== BlueXP  目前支援的網路功能

從 BlueXP  在 Azure NetApp Files 中設定 Volume 時，您現在可以指定網路功能。這與原生 Azure NetApp Files 中可用的功能一致。



=== 2024 年 6 月 12 日



==== 需要新權限

現在需要具備下列權限才能從 BlueXP 管理 Azure NetApp Files 磁碟區：

Microsoft.Network/virtualNetworks/subnets/read

讀取虛擬網路子網路需要此權限。

如果您目前是從 BlueXP 管理 Azure NetApp Files 、則需要將此權限新增至與您先前建立的 Microsoft Entra 應用程式相關聯的自訂角色。

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["瞭解如何設定 Microsoft Entra 應用程式、以及檢視自訂角色權限"]。



=== 2024 年 4 月 22 日



==== 不再支援 Volume 範本

您無法再從範本建立磁碟區。此動作與 BlueXP 補救服務相關聯、此服務已無法使用。



== 備份與還原



=== 2025 年 4 月 16 日

此 BlueXP  備份與還原版本包含下列更新。



==== UI 改善

此版本可簡化介面，提升您的使用體驗：

* 將 Aggregate 資料行從 Volumes 資料表中移除，以及從 V2 Dashboard 的 Volume 資料表中移除 Snapshot Policy ， Backup Policy 和 Replication Policy 資料行，將會產生更精簡的配置。
* 從下拉式清單中排除未啟動的工作環境，可減少介面雜亂，導覽效率更高，載入速度更快。
* 在標記欄上排序已停用時，您仍可檢視標記，確保重要資訊仍可輕鬆存取。
* 移除保護圖示上的標籤有助於更簡潔的外觀，並減少載入時間。
* 在工作環境啟動程序期間，對話方塊會顯示一個載入圖示，以提供意見回饋，直到探索程序完成為止，以提高系統作業的透明度和信心。




==== 增強型 Volume Dashboard （預覽）

Volume Dashboard 現在可在 10 秒內完成載入，提供更快，更有效率的介面。此預覽版本可提供給特定客戶，讓他們及早瞭解這些改善項目。



==== 支援第三方 WASBI 物件存放區（預覽）

BlueXP  備份與還原現在將支援延伸至第三方物件儲存區，主要著重於 WASBI 。這項新的預覽功能可讓您運用任何與 S3 相容的物件儲存區，滿足備份與還原需求。



===== WASBI 入門

若要開始使用第三方儲存設備做為物件存放區，您必須在 BlueXP  Connector 中啟用旗標。然後，您可以輸入第三方物件存放區的連線詳細資料，並將其整合至備份與還原工作流程。

.步驟
. SSH 連接到您的連接器。
. 進入 BlueXP  備份與恢復 CBS 伺服器容器：
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 透過 VIM 或任何其他編輯器開啟 `default.json`資料夾內的檔案 `config`：
+
[listing]
----
vi default.json
----
. 修改 `allow-s3-compatible`： false 至 `allow-s3-compatible`： true 。
. 儲存變更。
. 從容器結束。
. 重新啟動 BlueXP  備份與恢復 CBS 伺服器容器。


.結果
容器再次開啟後，開啟 BlueXP  備份與還原 UI 。當您開始備份或編輯備份策略時，您會看到新的供應商「 S3 相容」清單，以及 AWS ， Microsoft Azure ， Google Cloud ， StorageGRID 和 ONTAP S3 的其他備份供應商。



===== 預覽模式限制

在預覽此功能時，請考慮下列限制：

* 不支援自帶鏟斗（ BYOB ）。
* 不支援在原則中啟用 DataLock 。
* 不支援在原則中啟用歸檔模式。
* 僅支援內部部署 ONTAP 環境。
* 不支援 MetroCluster 。
* 不支援啟用貯體層級加密的選項。


在此預覽期間，我們鼓勵您探索這項新功能，並在完整功能推出之前，提供與協力廠商物件存放區整合的意見反應。



=== 2025 年 3 月 17 日

此 BlueXP  備份與還原版本包含下列更新。



==== SMB 快照瀏覽

此 BlueXP  備份與還原更新解決了一項問題，使客戶無法在 SMB 環境中瀏覽本機快照。



==== AWS GovCloud 環境更新

此 BlueXP  備份與還原更新解決了由於 TLS 憑證錯誤而導致 UI 無法連線至 AWS GovCloud 環境的問題。此問題已透過使用 BlueXP  Connector 主機名稱而非 IP 位址來解決。



==== 備份原則保留限制

以前， BlueXP  備份與還原 UI 將備份限制為 999 份，而 CLI 則允許更多複本。現在，您可以將多達 4 ， 000 個磁碟區附加至備份原則，並包含 1 ， 018 個未附加至備份原則的磁碟區。此更新包含其他驗證，可避免超過這些限制。



==== SnapMirror 雲端重新同步

此更新可確保在刪除 SnapMirror 關係之後，無法從不支援的 ONTAP 版本的 BlueXP  備份與還原啟動 SnapMirror 雲端重新同步。



=== 2025 年 21 月 2 日

此 BlueXP  備份與還原版本包含下列更新。



==== 高效能索引

BlueXP  備份與還原引進更新的索引功能，可讓來源工作環境上的資料索引更有效率。新的索引功能包括 UI 更新，還原資料的「搜尋與還原」方法效能提升，全球搜尋功能升級，擴充性更佳。

以下是改善項目的細目：

* * 資料夾整合 * ：更新版本會使用包含特定識別碼的名稱將資料夾群組在一起，使索引程序更順暢。
* * 硬碟檔案壓縮 * ：更新版本可減少用於建立每個磁碟區索引的檔案數量，簡化程序並免除額外資料庫的需求。
* * 以更多工作階段進行橫向擴充 * ：新版本新增更多工作階段來處理索引工作，加速程序。
* * 支援多個索引容器 * ：新版本使用多個容器來更好地管理及散佈索引工作。
* * 分割索引工作流程 * ：新版本將索引程序分為兩個部分，以提升效率。
* * 改善的並行處理 * ：新版本可同時刪除或移動目錄，加速索引程序。


.誰能從這項功能中獲益？
所有新客戶都能使用新的索引功能。

.如何啟用索引？
在您使用「搜尋與還原」方法還原資料之前，您必須先在每個準備還原磁碟區或檔案的來源工作環境上啟用「索引」。這可讓「索引型錄」追蹤每個磁碟區和每個備份檔案，讓您的搜尋快速又有效率。

執行「搜尋與還原」時，選取「啟用索引」選項，即可在來源工作環境上啟用索引。

有關詳細信息，請參閱文檔 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["如何使用搜尋擴大機還原 ONTAP 資料；還原"]。

.支援的擴充
新的索引功能支援下列項目：

* 不到 3 分鐘即可達到全域搜尋效率
* 多達 50 億個檔案
* 每個叢集最多 5000 個磁碟區
* 每個磁碟區最多可有 1 ，上限的快照
* 基準索引的最長時間少於 7 天。實際時間會因您的環境而異。




==== 全球搜尋效能提升

此版本也包含全球搜尋效能的增強功能。現在您將看到進度指標和更詳細的搜尋結果，包括檔案數和搜尋所需時間。專屬的搜尋和索引容器可確保在五分鐘內完成全域搜尋。

請注意下列與全域搜尋相關的考量事項：

* 新索引不會在標示為每小時的快照上執行。
* 新的索引功能僅適用於 FlexVols 上的快照，不適用於 FlexGroups 上的快照。




== 分類



=== 2025 年 12 月 5 日



==== 版本 1.43

此 BlueXP  分類版本包括：

.排定分類掃描的優先順序
BlueXP  分類現在可讓您在僅對應掃描之外，設定地圖和分類掃描的優先順序，讓您選擇先完成哪些掃描。在掃描開始期間和之前，都支援排列地圖和分類掃描的優先順序。如果您選擇在掃描進行期間排定優先順序，則對應和分類掃描都會排定優先順序。

如需更多資訊、請參閱 link:task-managing-repo-scanning.html#prioritize-scans["排定掃描的優先順序"]。

.支援加拿大個人識別資訊（ PII ）資料類別
BlueXP  分類掃描現在可識別加拿大 PII 資料類別，以取得所有省 / 地區的銀行資訊，護照號碼，社會保險號碼，以及駕照號碼和健康卡號碼。

如需更多詳細資訊xref:reference-private-data-categories.adoc#types-of-personal-data[個人資料類別]，請參閱。

.自訂分類（預覽）
BlueXP  分類現在支援自訂地圖分類和分類掃描。使用自訂分類，您可以量身打造 BlueXP  掃描，以擷取組織專屬的資料，確保符合規則運算式。此功能目前正在預覽中。

如需更多資訊、請參閱 xref:task-custom-classification.adoc[新增自訂分類]。

.儲存的搜尋索引標籤
**Policies ** 選項卡已重命名xref:task-using-policies.html[** 儲存的搜尋 **]。功能相同。

.將掃描事件傳送至 BlueXP  時間表
BlueXP  分類現在支援傳送分類事件（當掃描開始及結束時）至link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  時間表"^]。

.安全性更新
* Keras 套件已更新，可減輕資訊安全風險（ BDSA-2025-0107 和 BDSA-2025-1984 ）。
* Docker Container 組態已更新。容器不再能夠存取主機的網路介面來連接原始網路封包。透過減少不必要的存取，此更新可降低潛在的安全風險。


.效能增強
已實作程式碼增強功能，以減少 RAM 使用量，並改善 BlueXP  分類的整體效能。

.錯誤修正
導致 StorageGRID 掃描失敗的錯誤，無法載入調查頁面篩選選項，以及無法下載大量評估的資料探索評估已修正。



=== 2025 年 4 月 14 日



==== 版本 1.42

此 BlueXP  分類版本包括：

.大量掃描工作環境
BlueXP  分類現在支援工作環境的大量作業。您可以選擇啟用「對應掃描」，啟用「對應和分類掃描」，停用掃描，或在工作環境中跨磁碟區建立自訂組態。如果您為個別的 Volume 進行選擇，則會覆寫大量選擇。若要執行大量作業，請瀏覽至「 ** 組態 ** 」頁面並進行選擇。

.請在本機下載調查報告
BlueXP  分類現在支援從本機下載資料調查報告，以便在瀏覽器中檢視。如果您選擇本機選項，則資料調查只能以 CSV 格式進行，而且只會顯示前 10 ， 000 列的資料。

如需更多資訊、請參閱 link:task-investigate-data.html#create-the-data-investigation-report["使用 BlueXP  分類來調查組織中儲存的資料"]。



=== 2025 年 3 月 10 日



==== 版本 1.41

此 BlueXP  分類版本包含一般改良功能和錯誤修正。其中也包括：

.掃描狀態
BlueXP  分類現在會追蹤捲上 _initial_ 對應和分類掃描的即時進度。獨立的漸進式長條可追蹤對應和分類掃描，顯示掃描的檔案總數百分比。您也可以將游標暫留在進度列上，以檢視掃描的檔案數和檔案總數。追蹤掃描狀態可深入瞭解掃描進度，讓您更妥善地規劃掃描並瞭解資源分配。

若要檢視掃描的狀態，請瀏覽至 BlueXP  分類中的「 ** 組態 ** 」，然後選取「 ** 工作環境組態 ** 」。每個磁碟區的進度會以行顯示。



=== 2025 年 19 月 2 日



==== 版本 1.40

此 BlueXP  分類版本包含下列更新。

.支援 RHEL 9.5
除了先前支援的版本之外、此版本還支援 Red Hat Enterprise Linux v9.5 。這適用於任何手動內部部署的 BlueXP  分類安裝、包括暗點部署。

下列作業系統需要使用 Podman Container 引擎，而且需要 BlueXP  分類 1.30 版或更新版本： Red Hat Enterprise Linux 8.8 ， 8.10 ， 9.0 ， 9.1 ， 9.2 ， 9.3 ， 9.4 和 9.5 版。

.排定僅對應掃描的優先順序
執行僅對應掃描時，您可以優先處理最重要的掃描。當您有許多工作環境，且想要確保先完成高優先順序掃描時，此功能會有所幫助。

依預設，掃描會根據其啟動順序排入佇列。現在您可以將掃描排定優先順序，將掃描移到佇列的最前面。可以優先處理多個掃描。優先順序是以先出的順序指定，也就是您優先處理的第一次掃描會移到佇列前方；您優先處理的第二次掃描會成為佇列中的第二次掃描，依此類推。

優先順序是一次性授予。自動重新掃描對應資料會依預設順序進行。

優先順序僅限於link:concept-cloud-compliance.html["僅對應掃描"]；不適用於地圖和分類掃描。

如需更多資訊、請參閱 link:task-managing-repo-scanning.html#prioritize-scans["排定掃描的優先順序"]。

.重試所有掃描
BlueXP  分類現在支援批次重試所有失敗掃描的功能。

您現在可以使用「 ** 全部重試」功能，在批次作業中重新嘗試掃描。如果分類掃描因網路中斷等暫時性問題而失敗，您可以使用單一按鈕同時重試所有掃描，而無需個別重試。掃描可視需要重試多次。

若要重試所有掃描：

. 從 BlueXP  分類功能表中，選取 * 組態 * 。
. 若要重試所有失敗的掃描，請選取 * 重試所有掃描 * 。


.改善分類模型準確度
的機器學習模型準確度link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["預先定義的類別"]已提升 11% 。



=== 2025 年 1 月 22 日



==== 版本 1.39

此 BlueXP  分類版本會更新資料調查報告的匯出程序。此匯出更新可用於對資料執行其他分析，在資料上建立其他視覺效果，或與他人分享資料調查結果。

以前，資料調查報告匯出限制為 10 ， 000 列。此版本已移除限制，您可以匯出所有資料。這項變更可讓您從資料調查報告匯出更多資料，讓您在資料分析時更有彈性。

您可以選擇工作環境，磁碟區，目的地資料夾，以及 JSON 或 CSV 格式。匯出的檔案名稱包含時間戳記，可協助您識別資料匯出的時間。

支援的工作環境包括：

* Cloud Volumes ONTAP
* FSX ONTAP
* ONTAP
* 共用群組


從「資料調查」報告匯出資料具有下列限制：

* 每種類型（檔案，目錄和表格）的最大記錄下載量為 5 億筆。
* 100 萬筆記錄預計需要 35 分鐘才能匯出。


如需資料調查與報告的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["調查儲存在組織中的資料"]。



=== 2024 年 12 月 16 日



==== 版本 1.38

此 BlueXP  分類版本包含一般改良功能和錯誤修正。



== Cloud Volumes ONTAP



=== 2025 年 12 月 5 日



==== 探索透過 BlueXP  中的 Azure 市場所進行的部署

BlueXP  現在能夠探索直接透過 Azure 市場部署的 Cloud Volumes ONTAP 系統。這表示您現在可以將這些系統新增及管理為 BlueXP  中的工作環境，就像任何其他 Cloud Volumes ONTAP 系統一樣。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["從 Azure 市場部署 Cloud Volumes ONTAP"^]



==== 能夠為 Azure 租戶分層資料

您現在可以在由一個租戶建立 Cloud Volumes ONTAP 工作環境，並由另一個租戶建立 BlueXP  Connector 的情況下，為 Azure 租戶啟用分層。您可以使用此功能，為多個 Azure 租戶使用相同的 Connector 來分層資料。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Azure 租戶的分層資料需求"^]



=== 2025 年 4 月 16 日



==== Azure 支援的新區域

您現在可以在以下地區的單一和多個可用性區域中部署 Cloud Volumes ONTAP 9.12.1 GA 及更新版本。這包括支援單一節點和高可用度（ HA ）部署。

* 西班牙中部
* 墨西哥中部


有關所有區域的列表，請參閱 https://bluexp.netapp.com/cloud-volumes-global-regions["Azure 下的 Global Regions Map"^]。



=== 2025 年 4 月 14 日



==== 透過 Google Cloud 中的 API 自動建立儲存 VM

您現在可以使用 BlueXP  API ，在 Google Cloud 中自動建立儲存 VM 。您已在 Cloud Volumes ONTAP 高可用度（ HA ）組態中使用此功能，現在您也可以在單一節點部署中使用此功能。透過 BlueXP  API ，您可以在 Google Cloud 環境中輕鬆建立，重新命名及刪除其他資料服務儲存 VM ，而無需手動設定所需的網路介面，生命和管理生命。這項自動化可簡化儲存 VM 的管理程序。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["在 Google Cloud 中管理 Cloud Volumes ONTAP 的資料服務儲存 VM"^]



== 適用於 Google Cloud Cloud Volumes Service



=== 2020 年 9 月 9 日



==== 支援Cloud Volumes Service for Google Cloud

您現在Cloud Volumes Service 可以直接從BlueXP管理適用於Google Cloud的功能：

* 設定及建立工作環境
* 為Linux和UNIX用戶端建立及管理NFSv3和NFSv4.1磁碟區
* 為Windows用戶端建立及管理SMB 3.x磁碟區
* 建立、刪除及還原Volume快照




== 複製與同步



=== 2025 年 2 月 2 日



==== 新的作業系統支援資料代理程式

現在，執行 Red Hat Enterprise 9.4 ， Ubuntu 23.04 和 Ubuntu 24.04 的主機支援資料代理程式。

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["檢視 Linux 主機需求"]。



=== 2024 年 10 月 27 日



==== 錯誤修正

我們更新了 BlueXP 複本與同步服務、以及資料代理程式來修正一些錯誤。新的資料代理版本為 1.0.56 。



=== 2024 年 9 月 16 日



==== 錯誤修正

我們更新了 BlueXP 複本與同步服務、以及資料代理程式來修正一些錯誤。新的資料代理版本為 1.0.55 。



== 數位顧問



=== 2025 年 3 月 05 日



==== 升級顧問

* 現在您可以使用磁碟資格審查套件（ DQP ），根據預先定義的健全狀況和效能標準，自動更新磁碟控制器和儲存裝置韌體。如此可減少潛在故障，並提升整體系統可靠性。
* 我們引進時區資料庫（ DB ），以自動維持系統與最新時區定義的一致性。如此可確保即使時區規則變更，時間相關作業仍能順暢運作。




=== 2024 年 12 月 12 日



==== 升級顧問

您現在可以檢視建議更新的儲存韌體， SP / BMC 韌體和自動勒索軟體套件（ ARP ）。link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["瞭解如何檢視韌體更新建議"]。



=== 2024 年 12 月 04 日



==== AutoSupport Widget

AutoSupport Widget 已新增至主儀表板畫面，以警示客戶有關 AutoSupport 狀態相關問題的資訊。



== 數位錢包



=== 2025 年 3 月 10 日



==== 能夠移除訂閱

如果您已取消訂閱，現在可以從數位電子錢包中移除訂閱。



==== 檢視 Marketplace 訂閱的使用容量

檢視 PAYGO 訂閱時，您現在可以檢視訂閱的使用容量。



=== 2025 年 10 月 2 日

BlueXP  數位錢包經過重新設計，易於使用，現在提供額外的訂閱和授權管理功能。



==== 全新概觀儀表板

數位電子錢包首頁提供 NetApp 授權與 Marketplace 訂閱的更新儀表板，可深入瞭解特定服務，授權類型及必要行動。



==== 設定認證訂閱

BlueXP  數位電子錢包現在可讓您設定訂閱供應商認證。一般而言，當您第一次訂閱 Marketplace 訂閱或年度合約時，就會這麼做。先前只能在「認證」頁面上變更訂閱的認證。



==== 將訂閱與組織建立關聯

您現在可以更新訂閱直接從數位錢包關聯的組織。



==== 管理 Cloud Volume ONTAP 授權

您現在可以透過首頁或「 * 直接授權 * 」標籤來管理 Cloud Volumes ONTAP 授權。使用 * Marketplace 訂閱 * 索引標籤檢視您的訂閱資訊。



=== 2024 年 3 月 5 日



==== BlueXP 災難恢復

BlueXP 數位錢包現在可讓您管理 BlueXP 災難恢復的授權。您可以新增授權、更新授權、以及檢視授權容量的詳細資料。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["瞭解如何管理 BlueXP 資料服務的授權"]



=== 2023 年 30 月 7 日



==== 使用報告增強功能

Cloud Volumes ONTAP 使用率報告現在有幾項改善功能：

* TiB 單元現在已包含在欄名稱中。
* 現在包含序號的新 _ 節點 _ 欄位。
* 儲存 VM 使用量報告中現在包含新的 _ 工作負載類型 _ 欄。
* 工作環境名稱現在已包含在儲存 VM 和 Volume 使用量報告中。
* 現在、磁碟區類型 _file_ 會標示為 _ 主要（讀取 / 寫入） _ 。
* Volume 類型 _secondary_ 現在標示為 _Secondary （ DP ） _ 。


如需使用報告的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["下載使用報告"]。



== 災難恢復



=== 2025 年 13 月 5 日

版本 4.2.3



==== 子網路對應

在此版本中，您可以使用子網路對應，以新的方式管理容錯移轉時的 IP 位址，讓您為每個 vCenter 新增子網路。這樣做時，您可以定義每個虛擬網路的 IPv4 CIDR ，預設閘道和 DNS 。

在容錯移轉時， BlueXP  災難恢復會查看為對應虛擬網路提供的 CIDR ，並使用它來衍生新的 IP 位址，藉此判斷每個 vNIC 的適當 IP 位址。

例如：

* 網路 A = 10.1.1.0/24
* 網路 B = 192.168.1.0/24


VM1 具有連接至網路 A 的 VNIC （ 10.1.1.50 ）。網路 A 會對應到複寫計畫設定中的網路 B 。

在容錯移轉時， BlueXP  災難恢復會取代原始 IP 位址（ 10.1.1 ）的網路部分，並保留原始 IP 位址（ 10.1.1.50 ）的主機位址（ .50 ）。對於 VM1 ， BlueXP  災難恢復會查看網路 B 的 CIDR 設定，並使用網路 B 網路部份 192.168.1 ，同時保留主機部份（ .50 ）來為 VM1 建立新的 IP 位址。新 IP 會變成 192.168.1.50 。

總而言之，主機位址保持不變，而網路位址則會取代站台子網路對應中所設定的任何項目。這可讓您更輕鬆地在容錯移轉時管理 IP 位址重新指派，尤其是當您有數百個網路和數千個 VM 需要管理時。

有關在站點中包括子網映射的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["新增 vCenter 伺服器站台"]。



==== 跳過保護

您現在可以略過保護，這樣在複寫計畫容錯移轉之後，服務就不會自動建立反向保護關係。如果您想要在還原的網站上執行其他作業，然後在 BlueXP  災難恢復中將其重新上線，這項功能就很實用。

當您啟動容錯移轉時，如果原始來源站台在線上，依預設，服務會自動為複寫計畫中的每個磁碟區建立反向保護關係。這表示該服務會從目標站台建立 SnapMirror 關係，並將其還原至來源站台。當您啟動容錯回復時，服務也會自動反轉 SnapMirror 關係。

啟動容錯移轉時，您現在可以選擇 * 略過保護 * 選項。如此一來，服務就不會自動反轉 SnapMirror 關係。而是將可寫入的磁碟區保留在複寫計畫的兩側。

原始來源網站恢復上線後，您可以從「複寫計畫動作」功能表中選取「 * 保護資源 * 」，以建立反向保護。這會嘗試為計畫中的每個磁碟區建立反向複寫關係。您可以重複執行此工作，直到還原保護為止。還原保護時，您可以依照一般方式啟動容錯回復。

有關跳過保護的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式容錯移轉至遠端站台"]。



==== SnapMirror 會在複寫計畫中排程更新

BlueXP  災難恢復現在支援使用外部快照管理解決方案，例如原生 ONTAP SnapMirror 原則排程器或與 ONTAP 的協力廠商整合。如果複寫計畫中的每個資料存放區（ Volume ）都已有 SnapMirror 關係，而該關係正在其他地方管理，您可以將這些快照作為 BlueXP  災難恢復的恢復點。

若要設定，請在「複寫計畫」 > 「資源對應」區段中，勾選「設定資料存放區對應時，使用平台管理的備份和保留排程 * 」核取方塊。

選取此選項時， BlueXP  災難恢復不會設定備份排程。不過，您仍需要設定保留排程，因為仍可能需要拍攝快照來執行測試，容錯移轉和容錯回復作業。

設定此選項之後，服務不會定期擷取任何排程的快照，而是仰賴外部實體來拍攝和更新這些快照。

如需在複寫計畫中使用外部快照解決方案的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]。



=== 2025 年 4 月 16 日

版本 4.2.2



==== 虛擬機器排程探索

BlueXP  災難恢復每 24 小時執行一次發現。有了這個版本，您現在可以自訂探索排程，以滿足您的需求，並在需要時降低對效能的影響。例如，如果您有大量 VM ，則可以將探索排程設定為每 48 小時執行一次。如果 VM 數量不多，您可以將探索排程設定為每 12 小時執行一次。

如果您不想排程探索，您可以停用排程探索選項，並隨時手動重新整理探索。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["新增 vCenter 伺服器站台"]參閱。



==== 資源群組資料存放區支援

以前，您只能由 VM 建立資源群組。在此版本中，您可以依資料存放區建立資源群組。當您建立複寫計畫並為該計畫建立資源群組時，資料存放區中的所有 VM 都會列出。如果您有大量虛擬機器，而且想要依資料存放區將其分組，這項功能就很實用。

您可以使用下列方式建立具有資料存放區的資源群組：

* 當您使用資料存放區新增資源群組時，可以看到資料存放區清單。您可以選取一或多個資料存放區來建立資源群組。
* 當您建立複寫計畫並在計畫中建立資源群組時，可以在資料存放區中看到 VM 。


如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]參閱。



==== 免費試用或授權到期通知

此版本會通知您免費試用將在 60 天內到期，以確保您有時間取得授權。此版本也會在授權到期日提供通知。



==== 服務更新通知

在此版本中，頂端會出現橫幅，表示服務正在升級，且服務處於維護模式。升級服務時會顯示橫幅，升級完成後會消失。雖然您可以在升級進行期間繼續在 UI 中工作，但您無法提交新工作。排程工作會在更新完成後執行，服務會返回正式作業模式。



=== 2025 年 3 月 10 日

版本 4.2.1



==== 智慧型 Proxy 支援

BlueXP  Connector 支援智慧型 Proxy 。智慧型 Proxy 是一種輕量，安全且有效率的方法，可將內部環境連線至 BlueXP  服務。它可在您的環境和 BlueXP  服務之間提供安全連線，而不需要 VPN 或直接網際網路存取。這項最佳化的 Proxy 實作可卸載本機網路內的 API 流量。

設定 Proxy 時， BlueXP  災難恢復會嘗試直接與 VMware 或 ONTAP 通訊，並在直接通訊失敗時使用設定的 Proxy 。

BlueXP  災難恢復 Proxy 實作需要連接器與任何 vCenter Server 和 ONTAP 陣列之間使用 HTTPS 通訊協定進行連接埠 443 通訊。Connector 內的 BlueXP  災難恢復代理程式在執行任何動作時，會直接與 VMware vSphere ， VC 或 ONTAP 通訊。

如需 BlueXP  災難恢復智慧型 Proxy 的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["為 BlueXP 災難恢復設定基礎架構"]。

如需在 BlueXP  中設定一般 Proxy 的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["設定連接器以使用Proxy伺服器"^]。



==== 隨時結束免費試用

您可以在任何時間停止免費試用，也可以等到試用期到期。

請參閱。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["結束免費試用"]



=== 2025 年 19 月 2 日

版本 4.2



==== ASA R2 支援 VMFS 儲存設備上的 VM 和資料存放區

此版本的 BlueXP  災難恢復可為 VMFS 儲存設備上的虛擬機器和資料存放區提供 ASA R2 支援。在 ASA R2 系統上， ONTAP 軟體支援基本的 SAN 功能，同時移除 SAN 環境中不支援的功能。

此版本支援 ASA R2 的下列功能：

* 主要儲存設備的一致性群組資源配置（僅限平面一致性群組，表示只有一個層級沒有階層式結構）
* 備份（一致性群組）作業，包括 SnapMirror 自動化


BlueXP  災難恢復中對 ASA R2 的支援使用 ONTAP 9.16.1 。

雖然資料存放區可以掛載在 ONTAP 磁碟區或 ASA R2 儲存單元上，但 BlueXP  災難恢復中的資源群組不能同時包含來自 ONTAP 的資料存放區和來自 ASA R2 的資料存放區。您可以從 ONTAP 選取資料存放區，或從資源群組中的 ASA R2 選取資料存放區。



=== 2024 年 10 月 30 日



==== 報告

您現在可以產生及下載報告、以協助您分析環境。預先設計的報告會摘要容錯移轉和容錯移轉、顯示所有站台的複寫詳細資料、以及顯示過去七天的工作詳細資料。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["建立災難恢復報告"]。



==== 30 天免費試用

您現在可以註冊免費試用 30 天的 BlueXP  災難恢復。以前、免費試用期為 90 天。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["設定授權"]。



==== 停用及啟用複寫計畫

先前版本包含容錯移轉測試排程結構的更新、這是支援每日和每週排程所需的更新。此更新需要您停用並重新啟用所有現有的複寫計畫、才能使用新的每日和每週容錯移轉測試排程。這是一次性要求。

方法如下：

. 從上方功能表中、選取 * 複寫計畫 * 。
. 選取計畫、然後選取「動作」圖示以顯示下拉式功能表。
. 選擇*停用*。
. 幾分鐘後、選取 * 啟用 * 。




==== 資料夾對應

建立複寫計畫和對應運算資源時、您現在可以對應資料夾、以便將 VM 恢復到您指定的資料夾中、以供資料中心、叢集和主機使用。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]參閱。



==== VM 詳細資料可用於容錯移轉、容錯回復及測試容錯移轉

當發生故障、而您正在啟動容錯移轉、執行容錯回復或測試容錯移轉時、您現在可以查看 VM 的詳細資料、並識別哪些 VM 未重新啟動。

請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式容錯移轉至遠端站台"]。



==== VM 開機延遲、並依序執行開機順序

建立複寫計畫時、您現在可以為計畫中的每個 VM 設定開機延遲。這可讓您設定 VM 開始的順序、以確保在啟動後續優先順序 VM 之前、有一個 VM 正在執行所有優先順序。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]參閱。



==== VM 作業系統資訊

當您建立複寫計畫時、現在可以在計畫中看到每個 VM 的作業系統。這有助於決定如何將 VM 群組在資源群組中。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]參閱。



==== VM 名稱別名

當您建立複寫計畫時、現在可以在災難恢復會議上新增 VM 名稱的前置字元和後置字元。這可讓您在計畫中為 VM 使用更具描述性的名稱。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複寫計畫"]參閱。



==== 清理舊的快照

您可以刪除任何超出指定保留數量的不再需要的快照。快照可能會隨著時間而累積、因此您可以減少快照保留數量、然後移除快照以釋出空間。您可以隨時視需要或刪除複寫計畫來執行此作業。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理站台、資源群組、複寫計畫、資料存放區和虛擬機器資訊"]參閱。



==== 協調快照

您現在可以協調來源和目標之間不同步的快照。如果在 BlueXP  災難恢復之外的目標上刪除快照、可能會發生這種情況。服務會每 24 小時自動刪除來源上的快照。不過、您可以隨需執行此作業。此功能可讓您確保所有站台的快照一致。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理複寫計畫"]參閱。



== E系列系統



=== 2022 年 9 月 18 日



==== 支援E系列

您現在可以直接從 BlueXP 探索 E 系列系統。探索E系列系統可讓您完整檢視混合式多雲端的資料。



== 經濟效益



=== 2024 年 15 月 5 日



==== 停用的功能

部分 BlueXP  經濟效益功能已暫時停用：

* 技術更新
* 增加容量




=== 2024 年 3 月 14 日



==== 技術更新選項

如果您已有現有資產、並想要判斷是否需要更新技術、您可以使用 BlueXP 經濟效率技術更新選項。您可以檢閱目前工作負載的簡短評估並取得建議、或者如果您在過去 90 天內將 AutoSupport 記錄傳送至 NetApp 、該服務現在可以提供工作負載模擬、以瞭解工作負載在新硬體上的表現。

您也可以新增工作負載、並從模擬中排除現有的工作負載。

以前、您只能評估資產、並確定是否建議進行技術更新。

這項功能現在已納入左側導覽中的技術更新選項。

深入瞭解 https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["評估技術更新"]。



=== 2023 年 11 月 8 日



==== 技術更新

此版本的 BlueXP 經濟效益包括一個新選項、可評估您的資產、並識別是否建議更新技術。此服務包含左側導覽中的新 Tech Refresh 選項、您可以在其中評估目前工作負載和資產的新頁面、以及提供建議的報告。



== 邊緣快取

BlueXP  邊緣快取服務已於 2024 年 8 月 7 日移除。



== Google Cloud Storage



=== 2023 年 10 月 7 日



==== 能夠從 BlueXP 新增庫位並管理現有的庫位

您已有一段時間可以在 BlueXP Canvas 上檢視 Google Cloud Storage 儲存貯體。現在您可以直接從 BlueXP  新增新的貯體、並變更現有貯體的屬性。 https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["瞭解如何新增 Google Cloud Storage 貯體"]。



== Kubernetes

探索及管理 Kubernetes 叢集的支援已於 2024 年 8 月 7 日移除。



== 移轉報告

BlueXP  移轉報告服務已於 2024 年 8 月 7 日移除。



== 內部 ONTAP 部署的叢集



=== 2024 年 11 月 26 日



==== 支援採用私有模式的 ASA R2 系統

現在，您可以在私有模式中使用 BlueXP  時探索 NetApp ASA R2 系統。此支援自 BlueXP  3.9.46 私有模式版本開始提供。

* https://docs.netapp.com/us-en/asa-r2/index.html["深入瞭解 ASA R2 系統"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["瞭解 BlueXP 部署模式"^]




=== 2024 年 10 月 7 日



==== 支援 ASA R2 系統

在標準模式或受限模式下使用 BlueXP  時、您現在可以在 BlueXP  中探索 NetApp ASA R2 系統。當您發現 NetApp ASA R2 系統並開啟工作環境之後、系統管理員就會直接將您帶到系統管理員。

ASA R2 系統沒有其他管理選項可用。您無法使用標準檢視、也無法啟用 BlueXP 服務。

在私有模式中使用 BlueXP  時、不支援探索 ASA R2 系統。

* https://docs.netapp.com/us-en/asa-r2/index.html["深入瞭解 ASA R2 系統"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["瞭解 BlueXP 部署模式"^]




=== 2024 年 4 月 22 日



==== 不再支援 Volume 範本

您無法再從範本建立磁碟區。此動作與 BlueXP 補救服務相關聯、此服務已無法使用。



== 營運恢復能力



=== 2023 年 4 月 02 日



==== BlueXP  營運恢復服務

您可以使用新的 BlueXP 作業恢復服務及其自動化 IT 作業風險補救建議、在發生中斷或故障之前實作建議的修正。

營運恢復能力是一項服務、可協助您分析警示和事件、以維持服務和解決方案的健全狀況、正常運作時間和效能。

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["深入瞭解 BlueXP 作業恢復能力"]。



== 勒索軟體保護



=== 2025 年 4 月 29 日



==== 支援Amazon FSX for NetApp ONTAP 功能

此版本支援 Amazon FSX for NetApp ONTAP 。此功能可透過 BlueXP  勒索軟體保護，協助您保護適用於 ONTAP 工作負載的 FSX 。

適用於 ONTAP 的 FSX 是一項完全託管的服務，可在雲端提供 NetApp ONTAP 儲存設備的強大功能。它提供與內部部署相同的功能，效能和管理功能，以及原生 AWS 服務的敏捷度和擴充性。

BlueXP  勒索軟體保護工作流程已進行下列變更：

* 探索包括適用於 ONTAP 9.15 工作環境的 FSX 中的工作負載。
* Protection 索引標籤會顯示適用於 ONTAP 環境的 FSX 中的工作負載。在此環境中，您應該使用適用於 ONTAP 備份服務的 FSX 執行備份作業。您可以使用 BlueXP  勒索軟體保護快照來還原這些工作負載。
+

TIP: 無法在 BlueXP  中設定在適用於 ONTAP 的 FSX 上執行之工作負載的備份原則。在 Amazon FSX for NetApp ONTAP 中設定的任何現有備份原則都會保持不變。

* 警示事件會顯示適用於 ONTAP 工作環境的全新 FSX 。


如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["瞭解 BlueXP  勒索軟體保護與工作環境"]參閱。

如需支援選項的相關資訊，請參閱 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["BlueXP  勒索軟體保護限制"]。



=== 2025 年 4 月 14 日



==== 準備度訓練報告

此版本可讓您檢閱勒索軟體攻擊準備度訓練報告。整備訓練可讓您模擬對新建立的範例工作負載進行勒索軟體攻擊。然後，調查模擬攻擊並恢復範例工作負載。此功能可測試警示通知，回應和還原程序，協助您瞭解在發生實際勒索軟體攻擊時，您已做好準備。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["進行勒索軟體攻擊準備訓練"]參閱。



==== 新的角色型存取控制角色和權限

以前，您可以根據使用者的職責，將角色和權限指派給使用者，以協助您管理使用者對 BlueXP  勒索軟體保護的存取。在此版本中， BlueXP  勒索軟體保護有兩個新的角色，其中包含更新的權限。新角色包括：

* 勒索軟體保護管理員
* 勒索軟體保護檢視器


如需權限的詳細資訊，請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["BlueXP  勒索軟體保護功能的角色型存取"]參閱。



==== 付款改善

此版本包含多項付款程序的改善功能。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["設定授權和付款選項"]參閱。



=== 2025 年 3 月 10 日



==== 模擬攻擊和回應

在此版本中，模擬勒索軟體攻擊，測試您對勒索軟體警示的回應。此功能可測試警示通知，回應和還原程序，協助您瞭解在發生實際勒索軟體攻擊時，您已做好準備。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["進行勒索軟體攻擊準備訓練"]參閱。



==== 探索程序的增強功能

此版本包含選擇性探索和重新探索程序的增強功能：

* 使用此版本，您可以探索新增至先前所選工作環境的新建立工作負載。
* 您也可以在此版本中選取 _new_ 工作環境。此功能可協助您保護新增至環境的工作負載。
* 您可以在初始探索程序期間或在「設定」選項中執行這些探索程序。


如需詳細資訊，請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["探索先前所選工作環境的新建立工作負載"]參閱和 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["使用「設定」選項設定功能"]。



==== 偵測到高加密時發出警示

此版本可讓您在工作負載上偵測到高加密時，檢視警示，即使沒有高副檔名變更也沒問題。此功能使用 ONTAP 自主勒索軟體保護（ ARP ） AI ，可協助您識別有勒索軟體攻擊風險的工作負載。使用此功能，下載包含或不含副檔名變更的受影響檔案的完整清單。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["回應偵測到的勒索軟體警示"]參閱。



=== 2024 年 12 月 16 日



==== 使用 Data Infrastructure Insights Storage Workload Security 偵測異常的使用者行為

在此版本中，您可以使用 Data Infrastructure Insights Storage Workload Security 來偵測儲存工作負載中異常的使用者行為。此功能可協助您識別潛在的安全威脅，並封鎖潛在的惡意使用者，以保護您的資料。

如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["回應偵測到的勒索軟體警示"]參閱。

在使用 Data Infrastructure Insights Storage Workload Security 偵測異常使用者行為之前，您必須先使用 BlueXP  勒索軟體保護 * 設定 * 選項來設定選項。

請參閱 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["設定 BlueXP 勒索軟體保護設定"]。



==== 選取要探索及保護的工作負載

使用此版本，您現在可以執行下列動作：

* 在每個 Connector 中，選取您要探索工作負載的工作環境。如果您想要保護環境中的特定工作負載，而非其他工作負載，您可能會受益於此功能。
* 在工作負載探索期間，您可以針對每個 Connector 自動探索工作負載。此功能可讓您選取要保護的工作負載。
* 探索先前所選工作環境的新建立工作負載。


請參閱 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["探索工作負載"]。



== 補救

BlueXP 補救服務已於 2024 年 4 月 22 日移除。



== 複寫



=== 2022年9月18日



==== FSX for ONTAP Sfor Sfto Cloud Volumes ONTAP

您現在可以將資料從Amazon FSX for ONTAP Sfor Sfor Sfor Sf供 檔案系統複寫至Cloud Volumes ONTAP 支援功能。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["瞭解如何設定資料複寫"]。



=== 2022 年 31 月 7 日



==== FSX for ONTAP Sfor Sfor the Data來源

您現在可以將資料從Amazon FSX for ONTAP Sfingfile系統複寫到下列目的地：

* Amazon FSX for ONTAP Sf
* 內部部署 ONTAP 的叢集


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["瞭解如何設定資料複寫"]。



=== 2021 年 9 月 2 日



==== 支援Amazon FSX for ONTAP Sfy

您現在可以將資料從Cloud Volumes ONTAP 一套不間斷的系統或內部部署ONTAP 的一套功能的叢集複寫到Amazon FSX for ONTAP 整個檔案系統。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["瞭解如何設定資料複寫"]。



== 軟體更新



=== 2025 年 4 月 02 日



==== 降低風險

在 BlueXP  軟體更新的摘要區段中，您現在可以檢視作業系統更新可減輕的風險總數。這可讓使用者評估其安裝基礎上的安全性與穩定性改善。



=== 2024 年 8 月 7 日



==== ONTAP 更新

BlueXP  軟體更新服務可降低風險、確保客戶能充分運用 ONTAP 功能、為使用者提供順暢的更新體驗。

深入瞭解 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  軟體更新"]。



== StorageGRID



=== 2024 年 7 月 8 日



==== 全新進階檢視

從 StorageGRID 11.8 開始、您可以使用熟悉的 Grid Manager 介面、從 BlueXP  管理您的 StorageGRID 系統。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["瞭解如何使用進階檢視來管理 StorageGRID"]。



==== 能夠檢閱及核准 StorageGRID 管理介面憑證

您現在可以在從 BlueXP  探索 StorageGRID 系統時、檢閱及核准 StorageGRID 管理介面憑證。您也可以在探索到的網格上檢閱及核准最新的 StorageGRID 管理介面憑證。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["瞭解如何在系統探索期間檢閱及核准伺服器憑證。"]



=== 2022 年 9 月 18 日



==== 支援StorageGRID 功能

您現在StorageGRID 可以直接從BlueXP探索您的解決方案。探索StorageGRID 功能可讓您完整檢視混合式多雲端的資料。



== 分層



=== 2023 年 9 月 8 日



==== 使用自訂字首作為貯體名稱

在過去、您需要在定義貯體名稱時使用預設的「 Fabric Pool 」前置詞、例如 _Fabric Pool Bucket1_ 。現在、您可以在命名貯體時使用自訂首碼。只有在將資料分層至 Amazon S3 時、才能使用此功能。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["深入瞭解"]。



==== 在所有 BlueXP Connector 上搜尋叢集

如果您使用多個 Connectors 來管理環境中的所有儲存系統、則您要實作分層的某些叢集可能位於不同的 Connectors 。如果您不確定哪個 Connector 正在管理特定叢集、您可以使用 BlueXP 分層功能在所有 Connector 之間搜尋。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["深入瞭解"]。



=== 2023 年 4 月 7 日



==== 調整頻寬以傳輸非使用中資料

當您啟動 BlueXP 分層時、 ONTAP 可以使用無限量的網路頻寬、將非作用中的資料從叢集中的磁碟區傳輸到物件儲存區。如果您注意到分層流量會影響一般使用者工作負載，您可以限制傳輸期間可使用的頻寬量。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["深入瞭解"]。



==== 通知中心中顯示的分層事件

現在當叢集分層處理少於 20% 的冷資料（包括無資料分層的叢集）時、會出現分層事件「將額外資料從叢集 <name> 分層到物件儲存設備以提高儲存效率」、以作為通知。

此通知是一項「建議」、可協助您提高系統效率、並節省儲存成本。它提供的連結 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP 分層總擁有成本和節約計算機"^] 協助您計算成本節約效益。



=== 2023 年 4 月 3 日



==== 授權標籤已移除

授權標籤已從 BlueXP 分層介面中移除。所有隨用隨付（ PAYGO ）訂閱授權都可立即從 BlueXP 內部部署分層儀表板存取。您也可以從該頁面連結至 BlueXP 數位錢包、以便檢視和管理任何 BlueXP 分層自帶授權（ BYOL ）。



==== 分層索引標籤已重新命名及更新

「叢集儀表板」索引標籤已重新命名為「叢集」、「內部部署儀表板」索引標籤已重新命名為「內部部署儀表板」。這些頁面新增了一些資訊、可協助您評估是否能利用額外的分層組態來最佳化儲存空間。



== Volume 快取



=== 2023 年 6 月 4 日



==== Volume 快取

Volume 快取是 ONTAP 9 軟體的一項功能、是一項遠端快取功能、可簡化檔案發佈、減少 WAN 延遲、讓資源更接近使用者和運算資源的位置、並降低 WAN 頻寬成本。Volume 快取可在遠端位置提供持續且可寫入的 Volume 。您可以使用 BlueXP 磁碟區快取來加速資料存取、或卸載大量存取磁碟區的流量。快取磁碟區是讀取密集工作負載的理想選擇、尤其是用戶端需要重複存取相同資料的地方。

有了 BlueXP Volume 快取、您就能擁有雲端的快取功能、特別是適用於 NetApp ONTAP 、 Cloud Volumes ONTAP 的 Amazon FSX 、以及內部部署的工作環境。

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["深入瞭解 BlueXP Volume 快取"]。



== 工作負載工廠



=== 2025 年 04 月 5 日



==== CloudShell 自動完整支援

使用 BlueXP  工作負載原廠 CloudShell 時，您可以開始輸入命令，然後按 Tab 鍵檢視可用選項。如果存在多種可能性， CLI 會顯示建議清單。此功能可將錯誤降至最低，並加速命令執行，進而提升生產力。



==== 更新的權限術語

工作負載原廠使用者介面與文件現在使用「唯讀」來指稱讀取權限，而「讀取寫入」則指自動化權限。



=== 2025 年 3 月 30 日



==== CloudShell 會針對 ONTAP CLI 命令回報 AI 產生的錯誤回應

使用 CloudShell 時，每次您發出 ONTAP CLI 命令並發生錯誤時，您都可以取得 AI 產生的錯誤回應，包括故障說明，故障原因及詳細解決方法。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用 CloudShell"]



==== IAM ： SimulatePermissionPolicy 權限更新

現在您可以在工作負載原廠主控台管理 `iam:SimulatePrincipalPolicy`權限，只要新增額外的 AWS 帳戶認證，或新增 GenAI 工作負載等新工作負載功能即可。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["權限參考變更記錄"]



=== 2025 年 2 月 02 日



==== CloudShell 可在 BlueXP  工作負載原廠主控台取得

CloudShell 可從 BlueXP  工作負載原廠主控台的任何位置取得。CloudShell 可讓您使用 BlueXP  帳戶提供的 AWS 和 ONTAP 認證，並在類似 Shell 的環境中執行 AWS CLI 命令或 ONTAP CLI 命令。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用 CloudShell"]



==== 資料庫的權限更新

現在，下列權限可在 _read_ 模式下用於資料庫： `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["權限參考變更記錄"]
