= 新增支援功能、可將磁碟區備份至 S3 組態 ONTAP 系統上的貯體
:allow-uri-read: 


[IMPORTANT]
====
* 由於 Connector 具備重要的安全性增強功能、因此現在需要透過外部網際網路存取額外的端點、才能在公有雲環境中管理備份與還原資源。如果此端點尚未新增至防火牆的「允許」清單、您會在 UI 中看到「服務無法使用」或「無法判斷服務狀態」的錯誤：
+
\https://netapp-cloud-account.auth0.com

* 現在當您使用「 CVO 專業版」套件時、您必須訂閱備份與還原 PAYGO 、才能套裝 Cloud Volumes ONTAP 與 BlueXP 備份與還原。過去並不需要這麼做。符合資格的 Cloud Volumes ONTAP 系統的備份與還原訂閱不會產生任何費用、但在任何新磁碟區上設定備份時都需要付費。


====


=== 新增支援功能、可將磁碟區備份至 S3 組態 ONTAP 系統上的貯體

現在您可以使用已設定為簡易儲存服務（ S3 ）的 ONTAP 系統、將磁碟區備份至物件儲存。內部部署 ONTAP 系統和 Cloud Volumes ONTAP 系統皆支援此功能。此組態可在雲端部署和內部部署位置中支援、無需網際網路存取（「私有」模式部署）。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["深入瞭解"]。



=== 現在您可以在備份檔案中加入受保護磁碟區的現有 Snapshot

過去、您可以在初始備份檔案中將現有的 Snapshot 複本從讀寫磁碟區納入物件儲存區（而非從最新的 Snapshot 複本開始）。備份檔案中不包含來自唯讀磁碟區（資料保護磁碟區）的現有 Snapshot 複本。現在您可以選擇在「 DP 」磁碟區的備份檔案中包含較舊的 Snapshot 複本。

備份精靈會在備份步驟結束時顯示提示、您可以在其中選取這些「現有的快照」。



=== BlueXP 備份與還原不再支援未來新增的磁碟區自動備份

以前、您可以勾選備份精靈中的方塊、將選取的備份原則套用至未來新增至叢集的所有磁碟區。此功能已根據使用者的意見反應及缺乏使用此功能而移除。您需要手動啟用新增至叢集的任何新磁碟區備份。



=== 「工作監控」頁面已更新為新功能

「工作監控」頁面現在提供有關 3-2-1 備份策略的更多資訊。此服務也會提供與備份策略相關的其他警示通知。

「備份生命週期」類型篩選器已重新命名為「保留」。使用此篩選器可追蹤備份生命週期、並識別所有備份複本的到期日。「保留」工作類型會擷取在受 BlueXP 備份與還原保護的磁碟區上所起始的所有 Snapshot 刪除工作。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["深入瞭解更新的工作監控器"]。
